kind: Cluster
name: k8s-homelab
kubernetes:
  version: v1.33.10
talos:
  version: v1.12.6
---
kind: ControlPlane
machineClass:
  name: cp
  size: 3
---
kind: Workers
name: workers
machineClass:
  name: worker
  size: 6
