apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.19.2
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/cilium/values.yaml
    - repoURL: https://github.com/camcast3/the-basement.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: cilium-ca
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data
