apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      targetRevision: 0.35.1
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/descheduler/values.yaml
    - repoURL: https://github.com/camcast3/the-basement.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
