apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble-ui-route
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/camcast3/the-basement.git
    targetRevision: main
    path: kubernetes/infrastructure/hubble-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
