apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.17.4
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/rook-ceph-external/values.yaml
    - repoURL: https://github.com/camcast3/the-basement.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
