apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/spegel-org/helm-charts
      chart: spegel
      targetRevision: 0.6.0
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/spegel/values.yaml
    - repoURL: https://github.com/camcast3/the-basement.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: spegel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
