apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-proxies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/camcast3/the-basement.git
    targetRevision: main
    path: kubernetes/infrastructure/tailscale-operator
    directory:
      include: '{egress-*.yaml,ingress-*.yaml,infisical-secret.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
