# CloudNativePG operator Helm values
# Chart: cloudnative-pg (https://cloudnative-pg.github.io/charts)

crds:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 256Mi
