{
 "title": "Minecraft Server Monitor (mc-monitor)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(server_host)" } }
  ]
 },
 "panels": [
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_healthy{server_host=\"$server\",server_version=~\".+\"}",
     "legendFormat": "{{server_host}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{server_host=\"$server\"}",
     "legendFormat": "online"
    },
    {
     "expr": "minecraft_status_players_max_count{server_host=\"$server\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Minecraft Service - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=\"$server\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Minecraft Service - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"$server\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}
{
 "title": "Minecraft Server Stats (cpburnz/randombk)",
 "description": "Displays server stats exported by https://github.com/cpburnz/minecraft-prometheus-exporter",
 "tags": [
  "JVM",
  "minecraft"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded, application)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{application=\"$application\", instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Minecraft Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Players Online",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mc_player_list{application=\"$application\", instance=\"$instance\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# Chunks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "mc_dimension_chunks_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Tick Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_server_tick_seconds_bucket{application=\"$application\", instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "95th Percentile Tick Time by World",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_dimension_tick_seconds_bucket[$__rate_interval])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Tick Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "clamp_max(1 / histogram_quantile(0.95, sum(rate(mc_server_tick_seconds_bucket{application=\"$application\", instance=\"$instance\"}[$__rate_interval])) by (le)), 20)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tick Rate By World",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "clamp_max(1 / histogram_quantile(0.95, sum(rate(mc_dimension_tick_seconds_bucket[$__rate_interval])) by (name, le)), 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 23 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Eden",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Survivor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Old",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}
{
 "title": "BungeeCord / Velocity (Lobby)",
 "tags": [ "bungeecord" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "label_values(bungeecord_managed_servers, proxy_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (bungeecord_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Events per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bungeecord_player_chats_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "chats"
    },
    {
     "expr": "increase(bungeecord_server_list_pings_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "server list pings"
    },
    {
     "expr": "increase(bungeecord_player_connects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "connects"
    },
    {
     "expr": "increase(bungeecord_player_kicks_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "kicks"
    },
    {
     "expr": "increase(bungeecord_player_disconnects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (bungeecord_jvm_memory{type='used',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} used"
    },
    {
     "expr": "sum by (type) (bungeecord_jvm_memory{type='free',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} free"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_threads_current{proxy_name=~\"$proxy\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum by (state) (bungeecord_jvm_threads_state{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$proxy RAM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_jvm_memory{type='allocated', proxy_name=~\"$proxy\"}) - scalar(sum(bungeecord_jvm_memory{type='free', proxy_name=~\"$proxy\"}))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungeecord_jvm_memory{proxy_name=~\".*\"}) by (proxy_name))"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_managed_servers{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungeecord_installed_network_plugins{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungeecord_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "Online Player"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_max(avg(bungeecord_online_player_latency > 0),1000)",
     "legendFormat": "average player ping"
    }
   ]
  },
  {
   "title": "Online Player List",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 15 },
   "targets": [
    { "expr": "bungeecord_online_player > 0", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}